package com.mymeet.model;


/*
 * Participant represents the logical participant currently
 * present inside a MyMeet room.
 *
 * RoomManager owns the actual collection of Participant objects.
 *
 * Participant contains:
 *
 * - Identity information
 * - Current microphone state
 * - Current camera state
 * - Current screen-sharing state
 * - Current hand-raise state
 *
 *
 * These values represent the authoritative realtime state of
 * the participant while the participant is inside the room.
 *
 *
 * IMPORTANT:
 *
 * The actual audio/video/screen media is still handled by WebRTC.
 *
 * These fields only represent the current state that should be
 * visible to the other participants.
 *
 *
 * Example:
 *
 *     muted = true
 *
 * means:
 *
 *     "This participant is currently muted."
 *
 * It does NOT itself mute the WebRTC audio track.
 *
 * The frontend is responsible for changing the actual media track.
 * The backend synchronizes the resulting state with other clients.
 */
public class Participant {

    /*
     * Unique participant identity generated by the frontend.
     *
     * Example:
     *
     *     crypto.randomUUID()
     */
    private String participantId;


    /*
     * Display name shown to other participants.
     */
    private String name;


    /*
     * Microphone state.
     *
     * false = microphone is enabled
     * true  = microphone is muted
     */
    private boolean muted;


    /*
     * Camera state.
     *
     * false = camera is enabled
     * true  = camera is turned off
     */
    private boolean cameraOff;


    /*
     * Raise-hand state.
     *
     * false = hand is lowered
     * true  = hand is raised
     */
    private boolean handRaised;


    /*
     * Screen-sharing state.
     *
     * false = participant is not sharing their screen
     * true  = participant is currently sharing their screen
     */
    private boolean screenSharing;


    /*
     * Constructor used when a participant joins a room.
     *
     * Initial state:
     *
     *     muted         = false
     *     cameraOff     = false
     *     handRaised    = false
     *     screenSharing = false
     */
    public Participant(
            String participantId,
            String name
    ) {

        this.participantId = participantId;
        this.name = name;

        this.muted = false;
        this.cameraOff = false;
        this.handRaised = false;
        this.screenSharing = false;
    }


    /* =========================================================
       IDENTITY
       ========================================================= */

    public String getParticipantId() {

        return participantId;
    }


    public void setParticipantId(
            String participantId
    ) {

        this.participantId = participantId;
    }


    public String getName() {

        return name;
    }


    public void setName(
            String name
    ) {

        this.name = name;
    }


    /* =========================================================
       MICROPHONE
       ========================================================= */

    public boolean isMuted() {

        return muted;
    }


    public void setMuted(
            boolean muted
    ) {

        this.muted = muted;
    }


    /* =========================================================
       CAMERA
       ========================================================= */

    public boolean isCameraOff() {

        return cameraOff;
    }


    public void setCameraOff(
            boolean cameraOff
    ) {

        this.cameraOff = cameraOff;
    }


    /* =========================================================
       HAND RAISE
       ========================================================= */

    public boolean isHandRaised() {

        return handRaised;
    }


    public void setHandRaised(
            boolean handRaised
    ) {

        this.handRaised = handRaised;
    }


    /* =========================================================
       SCREEN SHARING
       ========================================================= */

    public boolean isScreenSharing() {

        return screenSharing;
    }


    public void setScreenSharing(
            boolean screenSharing
    ) {

        this.screenSharing = screenSharing;
    }
}