package com.mymeet.listener;

import com.mymeet.dto.MeetEvent;
import com.mymeet.dto.RoomState;
import com.mymeet.model.ParticipantSession;
import com.mymeet.service.ParticipantSessionService;
import com.mymeet.service.RoomService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.event.EventListener;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Component;
import org.springframework.web.socket.messaging.SessionDisconnectEvent;


/*
 * WebSocketEventListener handles lifecycle events generated by
 * Spring's WebSocket infrastructure.
 *
 * In MyMeet, the most important lifecycle event handled here is:
 *
 *     SessionDisconnectEvent
 *
 * This event allows the backend to clean up a participant even
 * when the frontend does not explicitly send:
 *
 *     /app/meet/leave
 *
 * Example:
 *
 *     Browser closes
 *          |
 *          v
 *     WebSocket disconnects
 *          |
 *          v
 *     SessionDisconnectEvent
 *          |
 *          v
 *     Find participant using sessionId
 *          |
 *          v
 *     Remove participant session
 *          |
 *          v
 *     Remove participant from room
 *          |
 *          v
 *     Broadcast updated ROOM_STATE
 *
 * This prevents stale participants from remaining in the
 * in-memory meeting state.
 */
@Component
public class WebSocketEventListener {

    /*
     * SLF4J logger is used instead of System.out.println().
     *
     * Debug-level logs are useful during development for tracing
     * WebSocket lifecycle events without producing unnecessary
     * output in normal production logging.
     */
    private static final Logger log =
            LoggerFactory.getLogger(WebSocketEventListener.class);

    private final ParticipantSessionService participantSessionService;
    private final RoomService roomService;
    private final SimpMessagingTemplate messagingTemplate;


    /*
     * ParticipantSessionService maintains the relationship:
     *
     *     WebSocket sessionId
     *             |
     *             v
     *     ParticipantSession
     *
     * RoomService maintains the actual room/participant state.
     *
     * SimpMessagingTemplate is responsible for notifying the
     * remaining participants about the updated room state.
     */
    public WebSocketEventListener(
            ParticipantSessionService participantSessionService,
            RoomService roomService,
            SimpMessagingTemplate messagingTemplate
    ) {
        this.participantSessionService = participantSessionService;
        this.roomService = roomService;
        this.messagingTemplate = messagingTemplate;
    }


    /*
     * Spring invokes this method whenever a WebSocket session
     * is disconnected.
     *
     * This is different from the explicit:
     *
     *     /app/meet/leave
     *
     * message.
     *
     * The disconnect event acts as a safety-net cleanup mechanism
     * for unexpected disconnections.
     */
    @EventListener
    public void handleWebSocketDisconnect(
            SessionDisconnectEvent event
    ) {

        /*
         * Every WebSocket connection has a unique session ID.
         *
         * The session ID is the key used by MyMeet to determine
         * which participant was associated with this connection.
         */
        String sessionId = event.getSessionId();

        log.debug(
                "WebSocket disconnected: sessionId={}",
                sessionId
        );


        /*
         * Remove the WebSocket-session -> participant mapping.
         *
         * This operation also tells us whether this session had
         * actually completed the JOIN process.
         */
        ParticipantSession participantSession =
                participantSessionService.remove(sessionId);


        /*
         * No mapping means either:
         *
         * 1. The participant already explicitly left.
         *
         *    In that case the participant-session mapping has
         *    already been removed, so there is nothing left to clean.
         *
         * 2. The WebSocket disconnected before JOIN completed.
         *
         *    Therefore no participant session was ever registered.
         *
         * In both cases, there is nothing for this listener to remove.
         */
        if (participantSession == null) {

            log.debug(
                    "No participant mapping found for sessionId={}",
                    sessionId
            );

            return;
        }


        /*
         * The ParticipantSession contains the information required
         * to locate the participant inside the room.
         */
        String roomId = participantSession.getRoomId();
        String participantId = participantSession.getParticipantId();

        log.debug(
                "Removing disconnected participant: participantId={}, roomId={}",
                participantId,
                roomId
        );


        /*
         * Remove the participant from the room.
         *
         * RoomService owns the room state, so the listener delegates
         * the actual room mutation instead of manipulating the room
         * directly.
         *
         * The returned RoomState represents the room after the
         * participant has been removed.
         */
        RoomState roomState = roomService.leave(
                roomId,
                participantId
        );


        /*
         * Create a ROOM_STATE event containing the updated room state.
         *
         * MyMeet uses ROOM_STATE to synchronize participants after
         * room membership changes.
         *
         * Important:
         *
         * ROOM_STATE is a synchronization event.
         *
         * It should not be treated by the frontend as an unlimited
         * WebRTC negotiation trigger.
         */
        MeetEvent eventMessage = new MeetEvent(
                "ROOM_STATE",
                roomState
        );


        /*
         * Broadcast the updated room state to every participant
         * subscribed to:
         *
         *     /topic/meet/{roomId}
         *
         * Example:
         *
         *     /topic/meet/demo
         *
         * The remaining clients receive the new participant list
         * and can update their local meeting state.
         */
        messagingTemplate.convertAndSend(
                "/topic/meet/" + roomId,
                eventMessage
        );


        /*
         * Useful for tracing the complete disconnect flow:
         *
         * WebSocket disconnected
         *     ->
         * participant session removed
         *     ->
         * participant removed from room
         *     ->
         * ROOM_STATE created
         *     ->
         * ROOM_STATE broadcast
         */
        log.debug(
                "ROOM_STATE broadcast after disconnect: roomId={}",
                roomId
        );
    }
}